name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]

env:
  NODE_VERSION: 18.16.0

jobs:
  linting:
    name: Linting
    timeout-minutes: 15
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup

      - name: Lint
        run: npm run lint

  type-check:
    name: Typescript
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup

      - name: Typescript
        run: npm run db:generate && npm run type-check

  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup

      - name: Prebuild
        run: npm run db:generate && CI=true SKIP_ENV_VALIDATION=1 npm run build
